services:
  frontend:
    build:
      context: frontend
    ports:
      - 8080:80
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network
    restart: always
    stdin_open: true
    depends_on:
      - backend

  backend:
    build:
      context: backend
    ports:
      - 3333:3333
      - 3001:9229
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network
      - data-network
    restart: unless-stopped
    depends_on:
      - mongo

  mongo:
    ports:
      - 27017:27017
    volumes:
      - ./database/docker-data:/data/db
    restart: always
    image: mongo:4.4.8
    networks:
      - data-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
  data-network:
