name: curiouser-paradox-workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  Initial-Commit-Status:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    steps:
      - name: Pending Status
        uses: myrotvorets/set-commit-status-action@master
        with:
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          token: ${{ secrets.API_TOKEN }}
          status: pending
  Angular-Tests:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    needs: Initial-Commit-Status
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test -- --watch=false --browsers=ChromeHeadless
  Workflow-Success:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    needs: [Angular-Tests, Initial-Commit-Status]
    steps:
      - name: Success Status
        uses: myrotvorets/set-commit-status-action@master
        with:
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          token: ${{ secrets.API_TOKEN }}
          status: success
  Workflow-Failure:
    timeout-minutes: 120
    runs-on: ubuntu-latest
    needs: [Angular-Tests, Initial-Commit-Status, Workflow-Success]
    steps:
      - name: Failure Status
        uses: myrotvorets/set-commit-status-action@master
        with:
          sha: ${{ steps.comment-branch.outputs.head_sha }}
          token: ${{ secrets.API_TOKEN }}
          status: failure
